export const GET_NAVIGATION_MAIN = 'GET_NAVIGATION_MAIN';


export const ACTIVE_MODAL_STATE = 'ACTIVE_MODAL_STATE';
export const DEACTIVE_MODAL_STATE = 'DEACTIVE_MODAL_STATE';


export const DEACTIVE_SUCCESS_MODAL_STATE = 'DEACTIVE_SUCCESS_MODAL_STATE';
export const ACTIVE_SUCCESS_MODAL_STATE = 'ACTIVE_SUCCESS_MODAL_STATE';


export const DEACTIVE_OVERLAY_STATE = 'DEACTIVE_OVERLAY_STATE';
export const ACTIVE_OVERLAY_STATE = 'ACTIVE_OVERLAY_STATE';





